# Blockchain Configuration
blockchain:
  network: ethereum
  node_url: https://mainnet.infura.io/v3/YOUR_INFURA_KEY
  chain_id: 1
  gas_limit: 6000000
  gas_price: auto
  contracts:
    identity_registry: "0x0000000000000000000000000000000000000000"
    verification: "0x0000000000000000000000000000000000000000"

# Database Configuration
database:
  type: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: your_password
  database_name: identity_verification

# AI and ML Configuration
ai:
  facial_recognition:
    model_path: models/facial_recognition
    confidence_threshold: 0.85
  document_verification:
    model_path: models/document_verification
    confidence_threshold: 0.90
  fraud_detection:
    model_path: models/fraud_detection
    anomaly_threshold: 0.75
  
# Cryptography Configuration
crypto:
  zkp:
    proving_key_path: keys/zkp_proving_key
    verification_key_path: keys/zkp_verification_key
  homomorphic:
    key_path: keys/homomorphic_key
    security_level: 128

# API Configuration
api:
  host: 0.0.0.0
  port: 8000
  debug: false
  enable_docs: true
  cors_origins:
    - http://localhost:3000
    - https://yourfrontend.com

# Security Configuration
security:
  jwt_secret: YOUR_JWT_SECRET
  token_expiry_minutes: 60
  password_min_length: 12
  max_login_attempts: 5

# Logging Configuration
logging:
  level: INFO
  file_path: logs/app.log
  rotation: 5 MB
  max_backups: 5

# Compliance Configuration
compliance:
  gdpr:
    enabled: true
    data_retention_days: 30
  ccpa:
    enabled: true 