from setuptools import setup, find_packages

setup(
    name="blockchain-identity-verification",
    version="0.1.0",
    description="Blockchain-Based AI for Privacy-Preserving Identity Verification",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "pycryptodome>=3.15.0",
        "web3>=5.30.0",
        "eth-brownie>=1.19.0",
        "fastapi>=0.88.0",
        "uvicorn>=0.20.0",
        "python-multipart>=0.0.5",
        "pydantic>=1.10.2",
        "tensorflow>=2.10.0",
        "scikit-learn>=1.2.0",
        "opencv-python>=4.6.0.66",
        "face-recognition>=1.3.0",
        "pysnark>=0.4.0",
        "tenseal>=0.3.10",
        "py-solc-x>=1.1.1",
        "pyjwt>=2.4.0",
        "pyyaml>=6.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
) 